######################################
#
# BUSCO summary figure
# @version 3.0.0
# @since BUSCO 2.0.0
# 
# Copyright (c) 2016-2017, Evgeny Zdobnov (ez@ezlab.org)
# Licensed under the MIT license. See LICENSE.md file.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("../results","hymen_all_busco.png",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO Assessment Results"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('SM-LHUM', 'SM-LHUM', 'SM-LHUM', 'SM-LHUM', 'SM-TCOR', 'SM-TCOR', 'SM-TCOR', 'SM-TCOR', 'SM-WAUR', 'SM-WAUR', 'SM-WAUR', 'SM-WAUR', 'SM-SINV', 'SM-SINV', 'SM-SINV', 'SM-SINV', 'SM-PGRA', 'SM-PGRA', 'SM-PGRA', 'SM-PGRA', 'SM-AZXXN', 'SM-AZXXN', 'SM-AZXXN', 'SM-AZXXN', 'SM-AZXXP', 'SM-AZXXP', 'SM-AZXXP', 'SM-AZXXP', 'SM-ACOL', 'SM-ACOL', 'SM-ACOL', 'SM-ACOL', 'SM-AZXXQ', 'SM-AZXXQ', 'SM-AZXXQ', 'SM-AZXXQ', 'SM-TSEP', 'SM-TSEP', 'SM-TSEP', 'SM-TSEP', 'SM-TZET', 'SM-TZET', 'SM-TZET', 'SM-TZET', 'SM-POGO', 'SM-POGO', 'SM-POGO', 'SM-POGO', 'SM-CFLO', 'SM-CFLO', 'SM-CFLO', 'SM-CFLO', 'SM-AZXXR', 'SM-AZXXR', 'SM-AZXXR', 'SM-AZXXR', 'SM-LNIG', 'SM-LNIG', 'SM-LNIG', 'SM-LNIG', 'SM-VEME', 'SM-VEME', 'SM-VEME', 'SM-VEME', 'SM-AZXXM', 'SM-AZXXM', 'SM-AZXXM', 'SM-AZXXM', 'SM-MPHA', 'SM-MPHA', 'SM-MPHA', 'SM-MPHA', 'SM-CBIR', 'SM-CBIR', 'SM-CBIR', 'SM-CBIR', 'SM-CCOS', 'SM-CCOS', 'SM-CCOS', 'SM-CCOS', 'SM-AZXXO', 'SM-AZXXO', 'SM-AZXXO', 'SM-AZXXO', 'SM-ACEP', 'SM-ACEP', 'SM-ACEP', 'SM-ACEP', 'SM-AJDMW', 'SM-AJDMW', 'SM-AJDMW', 'SM-AJDMW')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(97.2, 0.3, 1.9, 0.6, 90.8, 0.2, 3.8, 5.2, 97.3, 0.2, 1.8, 0.7, 85.5, 0.3, 5.3, 8.9, 86.7, 0.2, 6.2, 6.9, 96.4, 0.3, 2.2, 1.1, 95.7, 0.4, 2.4, 1.5, 90.1, 0.1, 3.6, 6.2, 96.7, 0.5, 1.8, 1.0, 97.4, 0.3, 1.6, 0.7, 97.2, 0.2, 2.0, 0.6, 94.2, 0.1, 4.6, 1.1, 97.2, 0.3, 1.9, 0.6, 97.3, 0.3, 1.6, 0.8, 87.5, 0.7, 8.8, 3.0, 94.3, 0.2, 3.3, 2.2, 96.6, 0.2, 2.4, 0.8, 90.0, 0.1, 4.0, 5.9, 96.8, 0.3, 2.1, 0.8, 96.9, 0.7, 1.7, 0.7, 96.9, 0.4, 2.0, 0.7, 94.5, 0.1, 4.0, 1.4, 96.4, 0.5, 2.1, 1.0)
my_values <- c(4293, 12, 83, 27, 4007, 11, 167, 230, 4296, 8, 78, 33, 3777, 12, 232, 394, 3827, 11, 274, 303, 4256, 15, 99, 45, 4226, 17, 107, 65, 3977, 6, 160, 272, 4270, 23, 81, 41, 4302, 15, 72, 26, 4292, 7, 90, 26, 4158, 4, 202, 51, 4292, 12, 86, 25, 4295, 15, 70, 35, 3862, 29, 388, 136, 4162, 11, 144, 98, 4264, 8, 107, 36, 3974, 5, 177, 259, 4275, 13, 91, 36, 4278, 29, 76, 32, 4279, 17, 87, 32, 4171, 6, 178, 60, 4257, 20, 94, 44)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
print("Done")
